// 
// Decompiled by Procyon v0.5.30
// 

package jeb.api;

public enum EngineOption
{
    APK_PARSE_DEX_ONLY("APK_PARSE_DEX_ONLY", 0), 
    APK_VERIFY("APK_VERIFY", 1), 
    DEX_CHECK_VERSION("DEX_CHECK_VERSION", 2), 
    DEX_CHECK_HASHES("DEX_CHECK_HASHES", 3), 
    DEX_CHECK_ACCESS_FLAGS("DEX_CHECK_ACCESS_FLAGS", 4), 
    DEX_PARSE_EXTENDED_OPCODES("DEX_PARSE_EXTENDED_OPCODES", 5), 
    DECOMP_METHOD_TIMEOUT("DECOMP_METHOD_TIMEOUT", 6), 
    DECOMP_PARSE_TRYCATCHES("DECOMP_PARSE_TRYCATCHES", 7), 
    DECOMP_OPT_AGGRESSIVE_SUBSTITUTIONS("DECOMP_OPT_AGGRESSIVE_SUBSTITUTIONS", 8), 
    DECOMP_AST_OPT_STRING_CONCAT("DECOMP_AST_OPT_STRING_CONCAT", 9), 
    DECOMP_AST_OPT_INLINE_SYNTH_ACCESSORS("DECOMP_AST_OPT_INLINE_SYNTH_ACCESSORS", 10), 
    DECOMP_AST_OPT_CREATE_FOR_LOOPS("DECOMP_AST_OPT_CREATE_FOR_LOOPS", 11), 
    DECOMP_AST_OPT_CREATE_VARARGS("DECOMP_AST_OPT_CREATE_VARARGS", 12), 
    DECOMP_AST_OPT_CREATE_MULTIDIMARRAYS("DECOMP_AST_OPT_CREATE_MULTIDIMARRAYS", 13), 
    DECOMP_AST_OPT_CREATE_CONDASSIGNS("DECOMP_AST_OPT_CREATE_CONDASSIGNS", 14);
    
    private EngineOption(final String s, final int n) {
    }
}
