package jeb.api;

public enum EngineOption {
   APK_PARSE_DEX_ONLY,
   APK_VERIFY,
   DEX_CHECK_VERSION,
   DEX_CHECK_HASHES,
   DEX_CHECK_ACCESS_FLAGS,
   DEX_PARSE_EXTENDED_OPCODES,
   DECOMP_METHOD_TIMEOUT,
   DECOMP_PARSE_TRYCATCHES,
   DECOMP_OPT_AGGRESSIVE_SUBSTITUTIONS,
   DECOMP_AST_OPT_STRING_CONCAT,
   DECOMP_AST_OPT_INLINE_SYNTH_ACCESSORS,
   DECOMP_AST_OPT_CREATE_FOR_LOOPS,
   DECOMP_AST_OPT_CREATE_VARARGS,
   DECOMP_AST_OPT_CREATE_MULTIDIMARRAYS,
   DECOMP_AST_OPT_CREATE_CONDASSIGNS;
}
